version: "3"
#
networks:
  default:
    driver: bridge
  kong-network:
    external:
      name: kong-network
#
services:
  #
  #######################################
  # PostgreSql: The database used by Konga
  #######################################
  konga_database:
    image: postgres:9.6-alpine
    restart: always
    volumes:
      - ./postgres/konga_database:/var/lib/postgresql/data
    environment:
      TZ: Asia/Bangkok
      POSTGRES_DB: konga
      POSTGRES_USER: konga
      POSTGRES_PASSWORD: konga
      POSTGRES_HOST_AUTH_METHOD: trust
  #
  #######################################
  # Konga database prepare
  #######################################
  konga_prepare:
    image: pantsel/konga:latest
    depends_on:
      - konga_database
    restart: on-failure
    command: "-c prepare -a postgres -u
      postgresql://konga:konga@konga_database/konga"
    environment:
      TZ: Asia/Bangkok
  #
  #######################################
  # Konga: Kong GUI
  #######################################
  konga:
    image: pantsel/konga:latest
    depends_on:
      - konga_prepare
    restart: always
    environment:
      TZ: Asia/Bangkok
      NODE_ENV: production
      DB_ADAPTER: postgres
      DB_URI: postgresql://konga:konga@konga_database/konga
    ports:
      - 1337:1337
    networks:
      - default
      - kong-network
